# Generated by Django 6.0.6 on 2026-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssne', '0002_aviso_bloco_setor_delete_aluno_delete_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='curso',
            field=models.CharField(blank=True, choices=[('INFO', 'Informática'), ('EDIFIC', 'Edificações'), ('MAMB', 'Meio Ambiente'), ('OUTRO', 'Outro')], help_text='Deixe em branco para exibir o aviso para todos os cursos.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, choices=[('INFO', 'Informática'), ('EDIFIC', 'Edificações'), ('MAMB', 'Meio Ambiente'), ('OUTRO', 'Outro')], max_length=10, null=True, verbose_name='Curso'),
        ),
    ]
